### ISSUE TITLE
Connect to TradeBot for users without Flo

### ISSUE THREAD

**Issue by DevonJames** [dloa/publisher-web#1]
Run this API endpoint, save the fields `weighted` and `USD` as `FloBTC` and `FloUSD`, respectively: http://api.alexandria.io/#get-market-data
Run this API endpoint, save the results as `floAvailable`: http://api.alexandria.io/#get-tradebot-balance-for-alexandria-io-node
Run this API endpoint, save the results as `tradebotBTCaddress`: http://api.alexandria.io/#get-a-bitcoin-address-from-alexandria-io-39-s-tradebot-node

### Register Publisher

`pubNameRegCostFlo` = $.01 / `FloUSD`
`pubNameRegCostBTC` = `pubNameRegCostFlo` x `FloBTC`

present them with a dialog box that says "You'll need approximately `pubNameRegCost` Florincoin tokens for this operation. Please send `pubNameRegCostBTC` BTC to this address: `tradebotBTCaddress`

### Publish Artifact

`artifactPubCostUSD` = `minBuy` / 100
`artifactPubCostFLO` = `artifactPubCostUSD` / `FloUSD`
`artifactPubCostBTC` = `artifactPubCostFLO` x `FloBTC`

present them with a dialog box that says "Because you are submitting a purchase price of `minBuy` for this artifact, your cost to publish it is `artifactPubCostUSD`. You'll need approximately `artifactPubCostFLO` Florincoin tokens for this operation. Please send `artifactPubCostBTC` BTC to this address: `tradebotBTCaddress`

**Comment by OstlerDev** [comment]
On hold until tradebot is fixed.

**Comment by OstlerDev** [comment]
to call up the tradebot interface use `tradebot(floaddress);`
