### ISSUE TITLE
I cannot publish Artifacts

### ISSUE THREAD

**Issue by Kodachi75** [dloa/publisher-web#31]
Each time when trying to publish a working Artifact to Alexandria, I arrive to the announcement that it will take around 2 minutes to publish my Artifact. Even after days, my Artifact does not publish to the Alexandria website. Alexandria does not even debit my wallet for the requisite Florincoins. Please advise.

**Comment by DevonJames** [comment]
@Kodachi75 please join our slack so we can help identify what is going wrong for you

dloaslack.bitspill.net

**Comment by OstlerDev** [comment]
@Kodachi75 I am going to mark this as closed as if I remember correctly we were able to fix your issue in the Slack.

If you are still having issues, please let me know and I will re-open this issue.
