### ISSUE TITLE
Drag + dropping multiple files into "media files" dropzone bug

### ISSUE THREAD

**Issue by copernicus-mogley** [dloa/publisher-web#32]
Browser stalls for a while and then adds the same file over and over and over again ...
![screenshot from 2016-10-23 13-37-28](https://cloud.githubusercontent.com/assets/6251098/19626432/4a9f60b6-9932-11e6-8463-9c4e945cf762.png)

**Comment by OstlerDev** [comment]
Fixed in commit 8ce3708c9d8d399c2d39b34054cc0e1c41fc9432
