### ISSUE TITLE
`hashes[mainHashIndex] is undefined`

### ISSUE THREAD

**Issue by OstlerDev** [dloa/publisher-web#37]
rtaylor [10:55 AM] 
Just ran into `hashes[mainHashIndex] is undefined`

[10:57]  
After 2 successful publishes

[10:57]  
Trying again

[10:58]  
And it happened again :disappointed:

[10:59]  
Going to try a different artifact

rtaylor [11:04 AM] 
That one worked. Interesting ... the one that failed is smaller (41MB) than all of the other artifacts that I'm publishing in this round.

**Comment by copernicus-mogley** [comment]
Error occurred 2x in a row, with separate artifacts. Successfully published both immediately after using /publisher.

**Comment by copernicus-mogley** [comment]
Then had it occurred with a completely different artfiact (using /publisher) ... subsequent attempt to publish using /publisher/dashboard also failed with same error.

**Comment by OstlerDev** [comment]
Fixed in latest 👍
