### ISSUE TITLE
Fix preview to show the correct name, player, and fix formatting

### ISSUE THREAD

**Issue by OstlerDev** [dloa/publisher-web#44]
preview still shows "Artist" instead of an actual artist name and the description doesn't show line breaks which is a little confusing.

**Comment by copernicus-mogley** [comment]
Fixed "Artist" display name (https://github.com/dloa/publisher-web/commit/38507b50cc0d3e1a421cfc5f0d584234fb61a8e5) but not line break issue, yet.

**Comment by copernicus-mogley** [comment]
Before closing, make preview player display properly for various artifact types.

**Comment by OstlerDev** [comment]
This should be fixed in the latest, you can take a look in `PhoenixUI.js` to see how easy it should be to change it up now :)
