### ISSUE TITLE
Wallet balance in sidebar bounces around during publishing

### ISSUE THREAD

**Issue by copernicus-mogley** [dloa/publisher-web#49]
It looks like it (sometimes) jumps around during publishing.

**Comment by copernicus-mogley** [comment]
Also reflects an incorrect balance in general.
![screenshot from 2017-04-01 16-42-42](https://cloud.githubusercontent.com/assets/6251098/24579755/8af2f622-16fb-11e7-815e-34309be40651.png)

**Comment by OstlerDev** [comment]
Implemented in latest 👍

**Comment by OstlerDev** [comment]
Well, fixed ;)
