### ISSUE TITLE
Add second-tier taxonomy

### ISSUE THREAD

**Issue by copernicus-mogley** [dloa/publisher-web#57]
After doing this ... https://github.com/dloa/publisher-web/issues/56

**Audio:** Music, Podcast, etc ... (see Soundcloud + archive.org)
**Video:** Film, Vehicles, Music, Animals, Sports, Travel, Events, Gaming, People, Podcast/Blog, Comedy, Entertainment, News/Politics, Howto, Style, Education, Science/Technology, Nonprofits/Activism (from YouTube, see also archive.org)
**Document:** Book, Recipe, Whitepaper, Manual ... (see archive.org)
**Thing:** 3d-Print, Sewing pattern, laser-cut ...

**Comment by OstlerDev** [comment]
I have added most of this in the newest publisher, take a look at it and reopen this if there still needs to be more :) it should be really easy to add them though with how I coded Phoenix 😄
