### ISSUE TITLE
Add "Publish Fee" value to the interface, w/ explanation button

### ISSUE THREAD

**Issue by DevonJames** [dloa/publisher-web#59]
•"Based on your pricing preferences, your publish fee will be: _____"
•Put an "i" (info) button near it that opens up an explanation, use 1 paragraph of Lorem Ipsum for now, will provide copy
•Live update the price when the user makes changes to their pricing preferences

**Comment by DevonJames** [comment]
![pricing info durring publish](https://cloud.githubusercontent.com/assets/7625406/25075102/1320a712-22c1-11e7-8e4a-79d6354d1807.png)

**Comment by OstlerDev** [comment]
Implemented in latest 👍
