### ISSUE TITLE
Must calculate the "Publish Fee" for the artifact

### ISSUE THREAD

**Issue by OstlerDev** [dloa/publisher-web#8]
Currently publishing only requires that a user spend the normal tx-fee for each transaction sent. In order to allow Alexandria's anti-spam minimum cost to remain independent of Florincoin's anti-spam minimum cost, the rules that govern publishing cost should be denominated in USD. The actual USD amount will vary over time until we find the right balance, but it should start at $0.01.

note the USD price to publish will be a variable determined by the Alexandria Council of Librarians

https://github.com/dloa/alexandria-browser/issues/12

**Comment by DevonJames** [comment]
Updated - fee is calculated by artifact's size for free artifacts, and by its price for commercial artifacts.

**Comment by OstlerDev** [comment]
Implemented in latest 👍
